FROM node:20-alpine as build

WORKDIR /app/frontend

COPY frontend/webpokerfront/package.json  ./
RUN npm install

COPY frontend/webpokerfront/ .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/frontend/build /usr/share/nginx/html
COPY --from=build /app/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
CMD [ "nginx", "-g", "daemon off;" ]

