# Generated by Django 5.1.1 on 2024-11-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poker_chips',
            field=models.IntegerField(default=0),
        ),
    ]
