# Generated by Django 5.1.1 on 2024-11-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_user_poker_chips'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
