# Generated by Django 5.1.1 on 2024-11-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_user_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='http://127.0.0.1:8000/static/profile_pictures/LuckyChip.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='poker_chips',
            field=models.IntegerField(default=5000),
        ),
    ]
