# Generated by Django 5.1.1 on 2024-12-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_lobbies_user_status_actions_lobbyinfo_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbies',
            name='current_players',
            field=models.IntegerField(default=0),
        ),
    ]
