# Generated by Django 5.1.1 on 2024-12-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0007_lobbies_current_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbies',
            name='lobby_name',
            field=models.CharField(default='lobby', max_length=15),
        ),
    ]
