# Generated by Django 5.1.1 on 2024-12-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0008_lobbies_lobby_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbies',
            name='max_bet',
        ),
    ]
